import React, {
  useEffect,
  useRef,
} from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAuth } from "../context/AuthContext";
import { sendRollRequest } from "../lib/get-account";
import { CashoutButton } from "../components/CashoutButton";
import { BlockList } from "../components/BlockList";
import { doConfetti } from "../lib/confetti";


const Home: NextPage = () => {
  const { user, balance, credit, login, logout, updateCredit } = useAuth();
  const blockListRef = useRef(null);
  const handlePlayClicked = () => {
    doConfetti();
    blockListRef.current?.spin();
    sendRollRequest().then(({ data }) => {
      setTimeout(() => {
        console.log("Data", data.result);
        blockListRef.current?.stopOn(data.result);
        setTimeout(() => {
          updateCredit(data.credit);
        }, 3000);
      }, 1500);
    });
  };

  useEffect(() => {
    const run = async () => {
      await login();
    };
    run();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Jackpot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jackpot!</h1>

        <p className={styles.description}>Pricenow coding challenge</p>
        <span>Balance: {balance}</span>
        <span>Credit: {credit}</span>

        <BlockList ref={blockListRef} />

        <button
          className="btn btn-primary btn-wide mt-5"
          onClick={handlePlayClicked}
        >
          Play
        </button>

        <CashoutButton className="mt-8" />
      </main>
    </div>
  );
};

export default Home;
